version: 2
jobs:
  build:
    working_directory: /go/src/github.com/SecureGovernment/tls-observatory
    docker:
      # replace with golang 1.11 when released
      - image: nvor/circleci:4458a35
      - image: circleci/postgres:10-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: observatory
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run: git submodule update --init
      - run: sudo apt-get update && sudo apt-get install dos2unix postgresql-client -y
      - run:
          name: Build TLS Observatory
          command: |
            make truststores cipherscan ciscotop1m alexatop1m
            make
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
